name: PHPUnit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: "MediaWiki ${{ matrix.mw }} | PHP ${{ matrix.php }} | MySQL ${{ matrix.mysql }}"
    continue-on-error: true
    strategy:
      matrix:
        include:
          # Latest stable MW - PHP 7.3
          - mw: 'REL1_36'
            php: 7.3
            mysql: '5.7'
            continue-on-error: false

          # Latest stable MW - PHP 7.4
          - mw: 'REL1_36'
            php: 7.4
            mysql: '5.7'
            continue-on-error: false

          # Latest MediaWiki release branch - PHP 7.3
          - mw: 'REL1_37'
            php: 7.3
            mysql: '5.7'
            continue-on-error: false

          # Latest MediaWiki release branch - PHP 7.4
          - mw: 'REL1_37'
            php: 7.4
            mysql: '5.7'
            continue-on-error: false

          # Latest MW master - PHP 7.3
          - mw: 'master'
            php: 7.3
            mysql: '5.7'
            continue-on-error: false

          # Latest MW master - PHP 7.4
          - mw: 'master'
            php: 7.4
            mysql: '5.7'
            continue-on-error: false

          # Latest MW master - PHP 8.0
          - mw: 'master'
            php: '8.0'
            mysql: '8.0'
            continue-on-error: true

          # Latest MW master - PHP 8.1
          - mw: 'master'
            php: 8.1
            mysql: '8.0'
            continue-on-error: true

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mediawiki
    services:
      mysql:
        image: mysql:${{ matrix.mysql }}
        options: --name integration-tests-mysql
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: mwtest
          MYSQL_USER: mwuser
          MYSQL_PASSWORD: mw12345
        ports:
        - 3306:3306
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl
          tools: composer:v2

      - name: Cache Composer cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: composer-php${{ matrix.php }}

      - name: Fetch MW install script
        uses: actions/checkout@v2
        with:
          path: installer

      - name: Download MediaWiki
        working-directory: ~
        run: bash installer/.github/workflows/download-mediawiki.sh ${{ matrix.mw }}

      - name: Install MediaWiki
        working-directory: ~
        run: bash installer/.github/workflows/install-mediawiki.sh
        env:
          MYSQL_DATABASE: mwtest
          MYSQL_USER: mwuser
          MYSQL_PASSWORD: mw12345

      - name: Checkout PortableInfobox extension
        uses: actions/checkout@v2
        with:
          path: mediawiki/extensions/PortableInfobox

      - name: Run PHPUnit
        continue-on-error: ${{ matrix.continue-on-error }}
        run: |
          [[ '${{ matrix.mw }}' != 'master' && '${{ matrix.mw }}' != 'REL1_37' ]] && PHPUNIT_ARGS='--use-normal-tables' ||  PHPUNIT_ARGS=''
          php tests/phpunit/phpunit.php $PHPUNIT_ARGS extensions/PortableInfobox/tests/phpunit
          python3 extensions/PortableInfobox/.github/workflows/phpunit-suite-edit "phpunit.xml.dist"
          php -d extension=pcov.so -d pcov.enabled=1 -d pcov.directory=. -d pcov.exclude='@(tests|vendor)@' \
          vendor/bin/phpunit \
          --exclude-group Dump,Broken,ParserFuzz,Stub \
          tests/phpunit/unit

        # In MediaWiki 1.37.0+ this is now an environmental variable
        env:
          PHPUNIT_USE_NORMAL_TABLES: 1
